language: clojure

jdk:
  - oraclejdk8

notifications:
  email: false

script:
  - lein test
  - lein codox

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master
